// Generado desde Listacontenidos.xlsx (pestaña 'Agrupaciones')
// Preferencia: columna 'Unnamed: 3' (Nuevo bloque); si vacío, 'Unnamed: 1'
window.AGRUPACIONES = {
  "BLOQUE 1: GENERAL": [
    "Tarea 1. Taller online 7. Módulo de diseño",
    "Cómo se configuran y para qué sirven las plantillas de roles",
    "Qué permisos necesito para editar el catálogo de procedimientos",
    "Qué permisos necesito para gestionar los órganos colegiados",
    "Qué permisos necesito para ver y enviar documentos a los libros oficiales",
    "Qué son las alertas, avisos y tareas de usuario",
    "Qué sistemas de identificación son válidos en sede electrónica",
    "Cómo funciona el Canal de Denuncias en sede electrónica",
    "Cómo se configura la firma biométrica",
    "Qué es y cómo funciona Gestiona-Envía",
    "Cómo crear y mantener Grupos en Gestiona",
    "Introducción y conceptos de la integración con el TEU del BOE para notificaciones infructuosas",
    "Cómo se configura el Canal de Denuncias",
    "Cómo se usa la APP móvil",
    "Cómo se configuran los escáneres",
    "Cómo funciona la base de datos de terceros",
    "Cómo se configuran las categorías personalizadas de Sede Electrónica",
    "Cómo se configura la cita previa",
    "Qué permisos son necesarios para Configuración general",
    "Conoce cada uno de los permisos de Gestiona",
    "Qué permisos necesito para atender a la ciudadanía",
    "Qué permisos necesito para configurar circuitos de tramitación",
    "Qué permisos necesito para tramitar expedientes",
    "Cómo gestionar el servicio de Cita previa en Gestiona",
    "Cómo se configura la App Móvil de Gestiona",
    "Qué es el proceso de ratificaciones",
    "Cómo se configura el chat de Gestiona",
    "Cómo se configura el Portal de Transparencia",
    "Cómo se configura la zona pública de la sede electrónica",
    "Qué es la Oficina de Asistencia en Materia de Registros (OAMR)",
    "Qué permisos necesito para la remisión de expedientes a juzgados a través de Inside",
    "Cómo es la firma electrónica de Gestiona",
    "Para qué sirve la página de Inicio",
    "Cómo se crean los libros oficiales",
    "Qué permisos necesito para trabajar en registro",
    "Qué permiso necesito para acceder a la auditoría de expedientes",
    "Qué son las notificaciones y las comunicaciones",
    "Qué es y como funcionan las videoconferencias de Gestiona",
    "Qué permisos necesito para configurar la sede electrónica",
    "Cómo funciona la Oficina de Asistencia en Materia de Registros (OAMR)",
    "Cómo se gestiona y mantiene la base de datos de terceros",
    "Cómo se configura la zona privada de la sede electrónica",
    "Cómo se configuran las notificaciones",
    "Cómo se configura Gestiona-Envía",
    "Qué permisos necesito para gestionar los órganos unipersonales",
    "Qué es y cómo funciona el Portal de Transparencia",
    "Cuáles son las características generales de la sede electrónica",
    "Qué permisos necesito para configurar textos predefinidos",
    "Permisos del canal de Denuncias",
    "Qué permisos necesito para publicar en la PCSP",
    "Cómo se configuran los datos de la entidad y el formato de documentos",
    "Qué permisos necesito para configurar circuitos de resolución",
    "Qué permisos necesito para trabajar con la cita previa",
    "Cómo funciona el Canal de Denuncias en Gestiona",
    "Cómo crear, gestionar y mantener usuarios en gestiona",
    "Cómo remitir  las salidas",
    "Cómo se gestionan los certificados electrónicos de la entidad",
    "Qué permisos son necesarios para la tramitación de documentos",
    "Qué permisos necesito para realizar publicaciones en la sede electrónica",
    "Test final: Configuración general de Gestiona",
    "Qué es y cómo funciona el módulo de libros oficiales",
    "Qué permisos necesito para configurar y gestionar la gestión documental y archivo (SGDA)",
    "Cómo solicitar cita previa desde la sede electrónica",
    "Cómo puedo identificarme como representante en sede electrónica",
    "Cómo acceder a Gestiona"
  ],
  "BLOQUE 2: GDA": [
    "Qué permisos necesito para la gestión de terceros",
    "Entregable taller online 1 - Tarea 2. Contextualización y configuración del catálogo",
    "Cómo se tramita con Markdown",
    "Cómo se configuran plantillas en Markdown",
    "Entregable taller online 3 - Tarea 1. Construcción de trámites inteligentes",
    "Qué son los Temas y Categorías de Registro",
    "Qué es el Inventario de trámites de la organización",
    "En qué consiste la gestión documental en Gestiona",
    "Cómo se configuran los trámites externos",
    "Qué son los activos semánticos",
    "Entregable taller online 2 - Tarea 1. Campos personalizados del tesauro",
    "Cómo se configuran los procedimientos",
    "Test final: Gestión documental y archivo",
    "Qué es el Módulo de Gestión Archivística",
    "Entregable taller online 1 - Tarea 1. Contextualización y configuración del catálogo",
    "Cómo se configuran las Actividades del catálogo",
    "Cómo configurar estados del expediente",
    "Cómo se configuran los campos del tesauro",
    "Cómo se configuran los Temas y Categorías de Registro",
    "Cómo se configura la función Section en Gestiona CODE",
    "Cómo se configura el Cuadro de clasificación archivística",
    "Cómo clasificar y archivar expedientes",
    "Cómo se configura la función Let en Gestiona CODE",
    "Qué es el  catálogo de actividades y procedimientos"
  ],
  "BLOQUE 3: REGLADA": [
    "Qué es y cómo funciona el Chat de Gestiona",
    "Qué es el circuito de tramitación",
    "Cómo se generan los acuerdos y el acta de un órgano colegiado",
    "Cómo funciona el circuito de resolución sin gasto",
    "Cómo se configura la tramitación reglada",
    "Cómo funciona el circuito de tramitación",
    "Resolución plural",
    "Test final: Tramitación Reglada",
    "Cómo se crean y configuran los órganos colegiados",
    "Entregable taller online 6 - Tarea 1. Simplificación administrativa",
    "Cómo se configuran los órganos unipersonales",
    "Cómo se configuran los procedimientos automatizados",
    "Qué son los órganos colegiados y unipersonales",
    "Qué es la tramitación reglada",
    "Resolución inicial",
    "Cómo se abre el expediente del órgano colegiado",
    "Entregable taller online 5 - Tarea 1. Circuito de resolución plural",
    "Cómo funciona la tramitación reglada",
    "Test final: Actos plurales",
    "Cómo se convoca un órgano colegiado",
    "Qué es el circuito de resolución",
    "Qué es un acto plural",
    "Cómo se configura el circuito de resolución sin gasto",
    "Cómo se realiza la revisión de los asuntos asignados al órgano colegiado",
    "Cómo se configura el circuito de tramitación",
    "Cómo se configura un acto plural",
    "Qué puede hacer un miembro de un órgano colegiado en la sede electrónica",
    "Test final: Escritorio de tramitación",
    "Qué es el Escritorio de Tramitación de Gestiona",
    "Entregable taller online 4 - Tarea 1. Circuito de resolución singular",
    "Cómo funcionan los actos plurales"
  ],
  "BLOQUE 4: ECONÓMICA": [
    "Modulo de ejecución: ¿Cómo se configura el circuito de resolución con fiscalización?",
    "¿Cuál es el alcance del módulo de Control Interno?",
    "Módulo de diseño: ¿Cómo puedo personalizar las actuaciones de control?",
    "Cómo debe actuar el área gestora cuando recibe el acuerdo adoptado por el órgano colegiado",
    "Conceptos. ¿Qué conceptos debo saber para entender el módulo de control interno?",
    "Tarea 2. Taller online 8. Circuitos de resolución con gasto",
    "Tarea 1. Taller online 8. Circuitos de resolución con gasto",
    "Módulo de ejecución: ¿Cómo se tramita el circuito de resolución con fiscalización?"
  ],
  "BLOQUE 5: ANALÍTICA": [
    "Test final: Módulo de ejecución",
    "Cómo funcionan las Búsquedas Avanzadas",
    "Qué es Analiza",
    "Test final: Analítica de datos",
    "Cómo se gestionan las hojas en Analiza",
    "Actividades TALLER 02. Gestiona Analiza. Conceptos y primeros pasos de configuración",
    "Cómo se dispone la información en Analiza",
    "Qué tipologías de gráficos de análisis y visualización de datos existen en Analiza",
    "Actividades TALLER 01. Búsquedas Avanzadas. Conceptos y opciones disponibles Instrucciones",
    "Cómo se crean y usan los marcadores",
    "Cómo se configuran las propiedades de los gráficos"
  ]
};